/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TherapistBridgeRouteImport } from './routes/therapist-bridge'
import { Route as IndexRouteImport } from './routes/index'

const TherapistBridgeRoute = TherapistBridgeRouteImport.update({
  id: '/therapist-bridge',
  path: '/therapist-bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/therapist-bridge': typeof TherapistBridgeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/therapist-bridge': typeof TherapistBridgeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/therapist-bridge': typeof TherapistBridgeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/therapist-bridge'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/therapist-bridge'
  id: '__root__' | '/' | '/therapist-bridge'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TherapistBridgeRoute: typeof TherapistBridgeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/therapist-bridge': {
      id: '/therapist-bridge'
      path: '/therapist-bridge'
      fullPath: '/therapist-bridge'
      preLoaderRoute: typeof TherapistBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TherapistBridgeRoute: TherapistBridgeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
